### ISSUE TITLE
Is it possible to provide the code for preprocessing Covertype dataset?

### ISSUE THREAD

**Issue by Nyte-BK201** [yandex-research/tabm#5]
I got some issues to fit my own dataset and it is a bit similar to Covertype. Can I have the preprocessing code for it so that I have a reference?

Also, I notice that the original Covertype has 54 features and the paper notes it with 15 numerical features + 4 binary features + 1 categorical feature. I would like to know why.

**Comment by Yura52** [comment]
If you are looking for a dataset with many binary features, unfortunately, covertype is rather not a good example here.

> 15 numerical features + 4 binary features + 1 categorical feature

It seems that there is a typo in the paper, thanks! It actually is 10 numerical features + 4 binary + 1 categorical, so 15 features in total.

> the original Covertype has 54 features

Among these 54 features, there are 40 binary features that are mutually exclusive (i.e. for any given object, exactly one of these 40 features equals 1.0 and the rest equal 0.0). This made us think that it is in fact the one-hot encoding of _one_ categorical feature. And, the [UCI page](https://archive.ics.uci.edu/dataset/31/covertype) of this dataset shows that there are indeed 40 `Soil_Type*` features, that look like the one-hot encoding of one cagegorical `Soil_Type` feature. So we replaced these 40 binary features with one categorical feature. Strictly speaking, it is not fully clear if our understanding is correct here, but I tend to believe so.

**Comment by Nyte-BK201** [comment]
> If you are looking for a dataset with many binary features, unfortunately, covertype is rather not a good example here.
Thanks for you suggestions. 

My dataset has 8 classes with 21 binary features and 35 numerical features. Please let me know if it is possible to share the preprocessing code of covertype or any other multiclass classification task. That will be extremely helpful for my setup and tuning :)

**Comment by Yura52** [comment]
@Nyte-BK201 do you need any further help with the Covertype dataset and preprocessing?

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
